sudo: required
dist: trusty
language: node_js
node_js:
  - 6.14.0
  - 8.11.4
env:
  global:
    - PATH="/tmp/ci-tools:./node_modules/.bin/:$PATH"
    - secure: RnOTVPol0b+qcwg3ac+hPRREA17qAQYlAV7ElZMUmWxkp5qzCVlIsHfxOHs08ZoA0S/wkwzL4RjwFeZBCbUwBLbwGdIKvWXqUPr3tZkw/EVOq713fAi5ORgHExI8DfofzHwyXMzgs0Bv9TFWiCa/xFtJ6/mZf0KmSrW3WBFMvB9IALa/JuyAfzeV2USQO0ddzmi8/pzbwFXmkaDYKjm6+YejfChE0/8WDkERugH8fKKEt9/peHiceqvqpnjmdSAFxM4I6nSYExIHvBnauWtB8+7T1/MmsHlhZPyy+/MJsn8QcsYxkkCUktVSCI7UEsnNuA1y8tBWsW9nNo+RsZMAQXfOU9M0W+qb3zjrsYNIXYVDollbwfDDy2pfQEoaI6nuhACW/Be+jgvRef5lBp5uQ5NpQIk0TzvnEtdn08xgxXsWOheHI4BOTJqQ7x9k+Ri8VoQ889L4dI7mNy7bTfsJDJtgazhOUEHqIyRtPIufo5qNbO9I6MpWdiLfZZr/yNMEwrhx7qLb6aqLGJrhFygi10r170Ix1c3CvnqLfsr50eccqS4YUS6sz95a6FBsOrwfO8+XyIQYmvHU0J2S8TMlG59DjfR3EfpkrCd08nH2b32eQTeyxm4JqJjMOAILofq2Lwl4lJd5d1OkZ7mxf9rzlVv133e6+i6eFMSsYrwGXhk= # NPM_AUTH
cache:
  yarn: true
  directories:
    - '/tmp/ci-tools'
before_install:
  - curl -sSL https://github.com/goodeggs/travis-utils/raw/master/install-ci-tools.sh
    | CACHE_DIR=/tmp/ci-tools sh -s -- yarn=1.9.4
  - yarn global add codecov
after_script:
  - codecov
install: yarn install
script: yarn run test
deploy:
  provider: script
  script: yarn publish
  skip_cleanup: true
  on:
    tags: true
    branch: master
