sudo: required
dist: trusty

language: node_js
node_js:
  - 6.9.1

cache:
  yarn: true
  directories:
    - "/home/travis/.npm"
    - /tmp/ci-tools

env:
  global:
    - PATH="/tmp/ci-tools:./node_modules/.bin/:$PATH"
    - NODE_ENV=test
    - FORCE_LOGS=yes

before_install: curl -sSL https://github.com/goodeggs/travis-utils/raw/master/install-ci-tools.sh | CACHE_DIR=/tmp/ci-tools sh -s -- yarn=0.21.3

install: yarn install

script: yarn test
