// flow-typed signature: 033de7d92329828c58b4f7fe0c957a8d
// flow-typed version: <<STUB>>/eslint-plugin-goodeggs_v7.3.2/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-goodeggs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-goodeggs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-goodeggs/lib/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-goodeggs/lib/test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-goodeggs/lib/utils/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-goodeggs/prettier-config' {
  declare module.exports: any;
}

declare module 'eslint-plugin-goodeggs/src/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-goodeggs/src/test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-goodeggs/src/utils/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-goodeggs/lib/index.js' {
  declare module.exports: $Exports<'eslint-plugin-goodeggs/lib/index'>;
}
declare module 'eslint-plugin-goodeggs/lib/test.js' {
  declare module.exports: $Exports<'eslint-plugin-goodeggs/lib/test'>;
}
declare module 'eslint-plugin-goodeggs/lib/utils/index.js' {
  declare module.exports: $Exports<'eslint-plugin-goodeggs/lib/utils/index'>;
}
declare module 'eslint-plugin-goodeggs/prettier-config.js' {
  declare module.exports: $Exports<'eslint-plugin-goodeggs/prettier-config'>;
}
declare module 'eslint-plugin-goodeggs/src/index.js' {
  declare module.exports: $Exports<'eslint-plugin-goodeggs/src/index'>;
}
declare module 'eslint-plugin-goodeggs/src/test.js' {
  declare module.exports: $Exports<'eslint-plugin-goodeggs/src/test'>;
}
declare module 'eslint-plugin-goodeggs/src/utils/index.js' {
  declare module.exports: $Exports<'eslint-plugin-goodeggs/src/utils/index'>;
}
