// flow-typed signature: 334377804717a8791c7760bdf5da7634
// flow-typed version: <<STUB>>/leasot_v^7.3.1/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'leasot'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'leasot' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'leasot/dist/cli/cli-reporter' {
  declare module.exports: any;
}

declare module 'leasot/dist/cli/cli' {
  declare module.exports: any;
}

declare module 'leasot/dist/cli/leasot-reporter' {
  declare module.exports: any;
}

declare module 'leasot/dist/cli/leasot' {
  declare module.exports: any;
}

declare module 'leasot/dist/definitions' {
  declare module.exports: any;
}

declare module 'leasot/dist/index' {
  declare module.exports: any;
}

declare module 'leasot/dist/lib/parsers' {
  declare module.exports: any;
}

declare module 'leasot/dist/lib/parsers/coffeeParser' {
  declare module.exports: any;
}

declare module 'leasot/dist/lib/parsers/defaultParser' {
  declare module.exports: any;
}

declare module 'leasot/dist/lib/parsers/ejsParser' {
  declare module.exports: any;
}

declare module 'leasot/dist/lib/parsers/erlangParser' {
  declare module.exports: any;
}

declare module 'leasot/dist/lib/parsers/hamlParser' {
  declare module.exports: any;
}

declare module 'leasot/dist/lib/parsers/haskellParser' {
  declare module.exports: any;
}

declare module 'leasot/dist/lib/parsers/hbsParser' {
  declare module.exports: any;
}

declare module 'leasot/dist/lib/parsers/jadeParser' {
  declare module.exports: any;
}

declare module 'leasot/dist/lib/parsers/latexParser' {
  declare module.exports: any;
}

declare module 'leasot/dist/lib/parsers/pascalParser' {
  declare module.exports: any;
}

declare module 'leasot/dist/lib/parsers/pythonParser' {
  declare module.exports: any;
}

declare module 'leasot/dist/lib/parsers/ssParser' {
  declare module.exports: any;
}

declare module 'leasot/dist/lib/parsers/twigParser' {
  declare module.exports: any;
}

declare module 'leasot/dist/lib/reporters' {
  declare module.exports: any;
}

declare module 'leasot/dist/lib/reporters/custom' {
  declare module.exports: any;
}

declare module 'leasot/dist/lib/reporters/json' {
  declare module.exports: any;
}

declare module 'leasot/dist/lib/reporters/markdown' {
  declare module.exports: any;
}

declare module 'leasot/dist/lib/reporters/raw' {
  declare module.exports: any;
}

declare module 'leasot/dist/lib/reporters/table' {
  declare module.exports: any;
}

declare module 'leasot/dist/lib/reporters/vscode' {
  declare module.exports: any;
}

declare module 'leasot/dist/lib/reporters/xml' {
  declare module.exports: any;
}

declare module 'leasot/dist/lib/utils/comments' {
  declare module.exports: any;
}

declare module 'leasot/dist/lib/utils/index' {
  declare module.exports: any;
}

declare module 'leasot/dist/types/json2xml' {
  declare module.exports: any;
}

// Filename aliases
declare module 'leasot/dist/cli/cli-reporter.js' {
  declare module.exports: $Exports<'leasot/dist/cli/cli-reporter'>;
}
declare module 'leasot/dist/cli/cli.js' {
  declare module.exports: $Exports<'leasot/dist/cli/cli'>;
}
declare module 'leasot/dist/cli/leasot-reporter.js' {
  declare module.exports: $Exports<'leasot/dist/cli/leasot-reporter'>;
}
declare module 'leasot/dist/cli/leasot.js' {
  declare module.exports: $Exports<'leasot/dist/cli/leasot'>;
}
declare module 'leasot/dist/definitions.js' {
  declare module.exports: $Exports<'leasot/dist/definitions'>;
}
declare module 'leasot/dist/index.js' {
  declare module.exports: $Exports<'leasot/dist/index'>;
}
declare module 'leasot/dist/lib/parsers.js' {
  declare module.exports: $Exports<'leasot/dist/lib/parsers'>;
}
declare module 'leasot/dist/lib/parsers/coffeeParser.js' {
  declare module.exports: $Exports<'leasot/dist/lib/parsers/coffeeParser'>;
}
declare module 'leasot/dist/lib/parsers/defaultParser.js' {
  declare module.exports: $Exports<'leasot/dist/lib/parsers/defaultParser'>;
}
declare module 'leasot/dist/lib/parsers/ejsParser.js' {
  declare module.exports: $Exports<'leasot/dist/lib/parsers/ejsParser'>;
}
declare module 'leasot/dist/lib/parsers/erlangParser.js' {
  declare module.exports: $Exports<'leasot/dist/lib/parsers/erlangParser'>;
}
declare module 'leasot/dist/lib/parsers/hamlParser.js' {
  declare module.exports: $Exports<'leasot/dist/lib/parsers/hamlParser'>;
}
declare module 'leasot/dist/lib/parsers/haskellParser.js' {
  declare module.exports: $Exports<'leasot/dist/lib/parsers/haskellParser'>;
}
declare module 'leasot/dist/lib/parsers/hbsParser.js' {
  declare module.exports: $Exports<'leasot/dist/lib/parsers/hbsParser'>;
}
declare module 'leasot/dist/lib/parsers/jadeParser.js' {
  declare module.exports: $Exports<'leasot/dist/lib/parsers/jadeParser'>;
}
declare module 'leasot/dist/lib/parsers/latexParser.js' {
  declare module.exports: $Exports<'leasot/dist/lib/parsers/latexParser'>;
}
declare module 'leasot/dist/lib/parsers/pascalParser.js' {
  declare module.exports: $Exports<'leasot/dist/lib/parsers/pascalParser'>;
}
declare module 'leasot/dist/lib/parsers/pythonParser.js' {
  declare module.exports: $Exports<'leasot/dist/lib/parsers/pythonParser'>;
}
declare module 'leasot/dist/lib/parsers/ssParser.js' {
  declare module.exports: $Exports<'leasot/dist/lib/parsers/ssParser'>;
}
declare module 'leasot/dist/lib/parsers/twigParser.js' {
  declare module.exports: $Exports<'leasot/dist/lib/parsers/twigParser'>;
}
declare module 'leasot/dist/lib/reporters.js' {
  declare module.exports: $Exports<'leasot/dist/lib/reporters'>;
}
declare module 'leasot/dist/lib/reporters/custom.js' {
  declare module.exports: $Exports<'leasot/dist/lib/reporters/custom'>;
}
declare module 'leasot/dist/lib/reporters/json.js' {
  declare module.exports: $Exports<'leasot/dist/lib/reporters/json'>;
}
declare module 'leasot/dist/lib/reporters/markdown.js' {
  declare module.exports: $Exports<'leasot/dist/lib/reporters/markdown'>;
}
declare module 'leasot/dist/lib/reporters/raw.js' {
  declare module.exports: $Exports<'leasot/dist/lib/reporters/raw'>;
}
declare module 'leasot/dist/lib/reporters/table.js' {
  declare module.exports: $Exports<'leasot/dist/lib/reporters/table'>;
}
declare module 'leasot/dist/lib/reporters/vscode.js' {
  declare module.exports: $Exports<'leasot/dist/lib/reporters/vscode'>;
}
declare module 'leasot/dist/lib/reporters/xml.js' {
  declare module.exports: $Exports<'leasot/dist/lib/reporters/xml'>;
}
declare module 'leasot/dist/lib/utils/comments.js' {
  declare module.exports: $Exports<'leasot/dist/lib/utils/comments'>;
}
declare module 'leasot/dist/lib/utils/index.js' {
  declare module.exports: $Exports<'leasot/dist/lib/utils/index'>;
}
declare module 'leasot/dist/types/json2xml.js' {
  declare module.exports: $Exports<'leasot/dist/types/json2xml'>;
}
